### ISSUE TITLE
Unable to disallow the add/remove + icon for other users

### ISSUE THREAD

**Issue by kumar2112** [pimcore-partner/output-data-config-toolkit#37]
Hi I have disallow the add/remove icon for classification store in my class defination
![image](https://user-images.githubusercontent.com/12470739/124914843-73afd800-e00e-11eb-9f64-08dad400db4c.png)
as you can see in image in .

Its working fine with super admin 
![image](https://user-images.githubusercontent.com/12470739/124914994-a063ef80-e00e-11eb-93b8-fa1bf6d8bcb2.png)

But when login from store user and open product attributes is show add/remove icon there.
![image](https://user-images.githubusercontent.com/12470739/124915103-cb4e4380-e00e-11eb-9b7f-91336b56cdac.png)

Some can help why this is showing dual behaviour

**Comment by fashxp** [comment]
this has nothing to do with this bundle and cannot be reproduced in pimcore core anyway. 

please double check, if behavior is still present in latest pimcore version, create an issue at pimcore/pimcore repository and provide steps to reproduce it in our demo application.
