### ISSUE TITLE
[Bug]: unable to remove config from an object

### ISSUE THREAD

**Issue by aweichler** [pimcore-partner/output-data-config-toolkit#55]
### Expected behavior

Press the remove button in the grid of the output channel config tab. The Item gets deleted.

### Actual behavior

The entry is not deleted. When inspecting the ajax call in the DEV tools of the browser you can see, that the config_id parameter get incremented.

### Steps to reproduce

Go to a [car](https://demo.pimcore.fun/admin/login/deeplink?object_313_object
) in the pimcore demo. Add add a config to a channel. Then try to remove. It should not be possible.

**Comment by aweichler** [comment]
@fashxp What do you think?
The issue is critical. Because every time you press delete on an item the id gets counted up an so other items might be deleted.

**Comment by aashan10** [comment]
@dvesh3 I could not link the pr #60 here. Could you please manually link the pr?

**Comment by dvesh3** [comment]
> @dvesh3 I could not link the pr #60 here. Could you please manually link the pr?

done

**Comment by aryaantony92** [comment]
Fixed by #60
