### ISSUE TITLE
[Bug]: Incompatible with Pimcore 10

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore-partner/output-data-config-toolkit#59]
### Expected behavior

Compatible with Pimcore ^10

### Actual behavior

Not compatible since it uses DB Helper functions that are introduced in Pimcore's 11.x Branch. Eg `Helper::quoteDataIdentifiers' 

https://github.com/pimcore/pimcore/blob/10.5/lib/Db/Helper.php 
https://github.com/pimcore/pimcore/blob/11.x/lib/Db/Helper.php

### Steps to reproduce

install on Pimcore 10

**Comment by blankse** [comment]
@dpfaffenbauer The current release should be compatible with Pimcore 10. I think the 5.x branch will only compatible with Pimcore 11. I changed the composer.json already in https://github.com/pimcore/output-data-config-toolkit/pull/58/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by dvesh3** [comment]
yes, the change was introduced on 5.x branch, which is compatible with only Pimcore 11 https://github.com/pimcore/output-data-config-toolkit/pull/56/files#diff-f9cebbdd4be9cb14976c67407e9d2c4b06cc9de0b772885a84e78de36bd8a42bR121
