### ISSUE TITLE
[Task] Verfiy identifyer quoting for formerly automatically quoted db calls

### ISSUE THREAD

**Issue by fashxp** [pimcore-partner/output-data-config-toolkit#64]
### Improvement description

related to https://github.com/pimcore/pimcore/issues/13392

check for 
- `->updateWhere(`

**Comment by kingjia90** [comment]
Closing the issue, there are no particular issues, just found this [case ](https://github.com/pimcore/output-data-config-toolkit/pull/75) but should be considered as a bug and is not strictly related to 11.x changes
