### ISSUE TITLE
[Improvement]: Decouple the bundle from ecommerce bundle

### ISSUE THREAD

**Issue by aweichler** [pimcore-partner/output-data-config-toolkit#89]
### Improvement description

I saw that this Bundle (v5) requires the ecommerce bundle, which is only used in one class. The ecommerce bundle has many dependencies.
Do you think it is possible to decouple the output data bundle from the ecommerce bundle?
Maybe with an interface? Or with checking if DefaultMockup class exists.

**Comment by dvesh3** [comment]
@aweichler yes, you are right. we should not require ecommerce bundle just for one reference. I have kicked the bundle requirement and added `class_exists` to checks https://github.com/pimcore/output-data-config-toolkit/pull/91. thanks for your report 😊
