### ISSUE TITLE
[Bug]: Fix green arrow icon

### ISSUE THREAD

**Issue by robertSt7** [pimcore-partner/output-data-config-toolkit#93]
### Expected behavior

![image](https://user-images.githubusercontent.com/104770750/172577353-cdd65efa-d9da-4cba-a28a-2b93d111f363.png)

### Actual behavior

<img width="824" alt="image" src="https://user-images.githubusercontent.com/104770750/172575580-ac7c6823-4a7a-4d38-bcc5-91e1d18a7f64.png">

### Steps to reproduce

- Create a "Favorite Output Channel Configuration"
- Open the "Output Channel Definition"

**Comment by kingjia90** [comment]
Also need to remove the "for" from the popup title, as in the Web2PrintTools it would display nothing after that.

**Comment by markus-moser** [comment]
> Also need to remove the "for" from the popup title, as in the Web2PrintTools it would display nothing after that.

I cannot find where it is like this. Currently the channel name is printed there:

![image](https://github.com/pimcore/output-data-config-toolkit/assets/4639428/9e4290ea-15dd-4bbb-a8d8-f18d7cb27495)

If this is still relevant, please create a separate issue.

The icon is solved, therefore I'll close this one.
