### ISSUE TITLE
[Bug]: 500 error for selecting type 

### ISSUE THREAD

**Issue by eraush** [pimcore-partner/output-data-config-toolkit#94]
### Expected behavior

No errors are thrown

### Actual behavior

Message: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-1-channel-marketplace' for key 'Unique'

### Steps to reproduce

1. Login with admin user
2. Navigate to `Customer Management Framework > Customers`
3. Click New Customer button
4. Switch to the last tab
5. Click Please select a type dropdown (or click Reload button)

![cms 500](https://user-images.githubusercontent.com/131660776/236806675-daf2ad98-1b25-453f-9a55-731b68a85197.png)
![select type 500](https://user-images.githubusercontent.com/131660776/236806680-4fec5069-468e-486a-ae10-1540ba4d3d9a.png)

**Comment by dvesh3** [comment]
already fixed by https://github.com/pimcore/output-data-config-toolkit/pull/90 on 5.x branch. @eraush please re-validate with latest changes on 5.x branch of output-data-config-toolkit.

**Comment by eraush** [comment]
fixed
